### ISSUE TITLE
panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by muggel042** [livekit/livekit#2019]
**Describe the bug**
After starting and running first test via example app on meet.livekit.io server crashes

**Server**
- Version: 1.4.5
- Environment: local Raspberry Pi 4 B
- any other information about your deployment setup

Server was set up using instructions from https://github.com/livekit/livekit#building-from-source
go version is go1.21.0 linux/arm64
Setup is very light. Only other component in use is nginx reverse proxy. No docker, no redis. Only low tech.

**Client**
https://meet.livekit.io/?tab=custom

**To Reproduce**
1. Start server manually livekit/bin/livekit-server --config livekit-config.yaml
2. Connect using token created via cli
3. Server crashes

**Expected behavior**
be able to connect

**Screenshots**
```
$ livekit/bin/livekit-server --config livekit-config.yaml --bind 127.0.0.1
2023-08-31T00:29:06.899+0200    INFO    livekit routing/interfaces.go:127       using single-node routing
2023-08-31T00:29:07.106+0200    WARN    livekit rtcconfig/rtc_unix.go:17        UDP receive buffer is too small for a production set-up {"current": 425984, "suggested": 5000000}
2023-08-31T00:29:07.107+0200    INFO    livekit service/turn.go:141     Starting TURN server    {"turn.relay_range_start": 30000, "turn.relay_range_end": 40000, "turn.portTLS": 5349, "turn.externalTLS": true, "turn.portUDP": 3478}
2023-08-31T00:29:07.109+0200    INFO    livekit service/server.go:236   starting LiveKit server {"portHttp": 7880, "nodeID": "ND_FhzG5P8S", "nodeIP": "192.168.1.65", "version": "1.4.5", "bindAddresses": ["127.0.0.1"], "rtc.portTCP": 7881, "rtc.portUDP": 7882, "portPrometheus": 6789}
panic: unaligned 64-bit atomic operation

goroutine 112 [running]:
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0x31b499c)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm.s:280 +0x14
go.uber.org/atomic.(*Int64).Load(...)
        /home/livekit/go/pkg/mod/go.uber.org/atomic@v1.11.0/int64.go:45
github.com/livekit/livekit-server/pkg/rtc.(*Room).FirstJoinedAt(...)
        /home/livekit/livekit/pkg/rtc/room.go:239
github.com/livekit/livekit-server/pkg/rtc.(*Room).Join(0x31b4780, {0xfef320, 0x24c9180}, {0xfe3ee4, 0x31ae0c0}, 0x2d57e60, {0x3212700, 0x1, 0x2})
        /home/livekit/livekit/pkg/rtc/room.go:290 +0x1cc
github.com/livekit/livekit-server/pkg/service.(*RoomManager).StartSession(0x2bbe360, {0xfe40c8, 0x31a0030}, {0x2ad49a8, 0x8}, {{0x2ad4a00, 0x5}, {0x2ad4c50, 0x5}, 0x0, ...}, ...)
        /home/livekit/livekit/pkg/service/roommanager.go:408 +0x1840
github.com/livekit/livekit-server/pkg/service.NewDefaultSignalServer.func1({0xfe40c8, 0x31a0030}, {0x2ad49a8, 0x8}, {{0x2ad4a00, 0x5}, {0x2ad4c50, 0x5}, 0x0, 0x0, ...}, ...)
        /home/livekit/livekit/pkg/service/signal.go:108 +0x2d4
github.com/livekit/livekit-server/pkg/service.(*signalService).RelaySignal(0x29941e0, {0xebefa8e8, 0x240e6c0})
        /home/livekit/livekit/pkg/service/signal.go:177 +0x52c
github.com/livekit/psrpc/pkg/server.(*streamHandler[...]).handleOpenRequest(0xfea678, 0x2613340, 0x2dec340, 0x298e2c0)
        /home/livekit/go/pkg/mod/github.com/livekit/psrpc@v0.3.3/pkg/server/stream.go:202 +0x618
github.com/livekit/psrpc/pkg/server.(*streamHandler[...]).handleRequest.func1()
        /home/livekit/go/pkg/mod/github.com/livekit/psrpc@v0.3.3/pkg/server/stream.go:141 +0x44
created by github.com/livekit/psrpc/pkg/server.(*streamHandler[...]).handleRequest in goroutine 108
        /home/livekit/go/pkg/mod/github.com/livekit/psrpc@v0.3.3/pkg/server/stream.go:140 +0xd4
```

**Additional context**
Also happens with older go version 1.18

**Comment by boks1971** [comment]
This is due to accessing 64-bit atomics on a 32-bit OS/arch. 

Code has to ensure alignment - https://blog.openziti.io/my-pi-day-journey-with-go-64-bit-alignment.

There is a proposal to do the alignment, but still open - https://github.com/golang/go/issues/36606.

Given that the code pattern is there in a few places, probably not going to support the 32-bit OS/arch for now.

**Comment by muggel042** [comment]
Thanks for checking. I'm not sure if this really is a 64bit OS:
https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/

There is an RPi 4 in use, with current OS.

**Comment by muggel042** [comment]
After re-installing as 64bit version, tests are running as expected.
