### ISSUE TITLE
Server restart with panic: non-positive interval for Ticker.Reset

### ISSUE THREAD

**Issue by xwrs** [livekit/livekit#2370]
**Describe the bug**
LiveKit server instance gets restarted with panic error

**Server**
- Version: 1.5.0
- Environment: k8s on baremetal instances
- any other information about your deployment setup

**Client**
- SDK: [e.g. js, ios]
- Version: [0.x.x]

**To Reproduce**
issue is sporadic

**Expected behavior**
LiveKit server must recover from such panic

**Screenshots**
N/A

**Additional context**
log:
```
panic: non-positive interval for Ticker.Reset

goroutine 735961208 [running]:
time.(*Ticker).Reset(0xc1d448e040?, 0x40000000000002c?)
	/usr/local/go/src/time/tick.go:55 +0x8f
github.com/livekit/mediatransportutil/pkg/twcc.(*Responder).changeTickerDelta(...)
	/workspace/pkg/mediatransportutil/pkg/twcc/twcc.go:116
github.com/livekit/mediatransportutil/pkg/twcc.(*Responder).Push(0xc13665a2a0, 0x3f00, 0xc17ab1fc58?, 0x1)
	/workspace/pkg/mediatransportutil/pkg/twcc/twcc.go:98 +0x26a
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).processHeaderExtensions(0xc0cf5c01e0, 0xc2a4e9e480, {0x437?, 0x2000?, 0x1e65f60?})
	/workspace/pkg/sfu/buffer/buffer.go:578 +0x22d
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).calc(0xc0cf5c01e0, {0xc0f3df2000, 0x437, 0x2000}, {0x10?, 0xafaa36?, 0x1e65f60?})
	/workspace/pkg/sfu/buffer/buffer.go:434 +0x13d
github.com/livekit/livekit-server/pkg/sfu/buffer.(*Buffer).Write(0xc0cf5c01e0, {0xc0f3df2000, 0x437, 0x2000})
	/workspace/pkg/sfu/buffer/buffer.go:289 +0x269
github.com/pion/srtp/v2.(*ReadStreamSRTP).write(0xc0bc60f260?, {0xc0f3df2000?, 0x437, 0x2000?})
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.17/stream_srtp.go:67 +0x30
github.com/pion/srtp/v2.(*SessionSRTP).decrypt(0xc1de00e480, {0xc0f3df2000, 0x441, 0x2000})
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.17/session_srtp.go:194 +0x1a5
github.com/pion/srtp/v2.(*session).start.func1()
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.17/session.go:152 +0x12e
created by github.com/pion/srtp/v2.(*session).start
	/go/pkg/mod/github.com/pion/srtp/v2@v2.0.17/session.go:131 +0x2cc
```

**Comment by boks1971** [comment]
This is puzzling. v1.5.0 of livekit server does not have that panic line of code. That code is old and has been redone about 3 months ago. This is the version of `mediatransportutil` repo in v1.5.0 release of server - https://github.com/livekit/mediatransportutil/tree/c137afffe71c57596896b12b0d855e63021d2418. And that file (twcc.go) is only 74 lines.

Can you please try the latest version of the server if possible?

**Comment by davidzhao** [comment]
closing as no response is received
