### ISSUE TITLE
Possible deadlock condition hangs the server when ending screen share

### ISSUE THREAD

**Issue by rishabhrao** [livekit/livekit#3297]
**Describe the bug**
The livekit server hangs and is completely unavailable for a few minutes after repeatedly starting and stopping screen share.

**Server**
- Version: 1.8.0
- Environment: a self-hosted `c2d-highcpu-4` GCP instance booted with startup script generated by `livekit/generate`, bundled redis.

**Client**
- Joined with custom server details in meet.livekit.io 

**To Reproduce**
1. Three clients are connected to the room
2. All clients start and stop screen share a few times.
3. One time, while stopping the screen share track, the server goes into some kind of deadlock condition, and everything freezes for all connected clients.
4. On the server side, if you run `docker logs <server_container>`, the log output also seems to have frozen completely in the middle, some time after a `resolved track` log. Once the server is out of its deadlock after a few mins, the log continues.

**Expected behavior**
The server shouldn't freeze.

**Additional context**
- The host itself seems to be perfectly fine, the livekit process isn't using up a lot of CPU, memory, disk, network, etc. yet the server process is frozen for a few minutes while nothing works.
- We've ensured the system ulimit is increased, so that's not an issue.
- After 5-10 mins, the server recovers by itself, and everything starts working again.
- When the server is in this deadlock condition, the rest API endpoint returns `OK` if opened in the browser, however, any calls to `join participant` or `listRooms` times out. The connected clients also drop the websocket connection and fail to reconnect until the server is back up.
- We can reliably reproduce this issue, we have tried it on multiple servers, and we have also tried it by building the docker image from the latest commit in the master branch.

**Comment by boks1971** [comment]
Can you share server logs and goroutine dump?

**Comment by wurucu** [comment]
the same error happens to me too.
Server : v1.8.4
Client JS Sdk : 2.9.5
Kubernetes - 2 Livekit Pod (DaemonSets)

Livekit Config : 
```
rtc:
  tcp_port: 7881
  use_ice_lite: true
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: true
  allow_tcp_fallback: true
  stun_servers:
    - stun.cloudflare.com:3478
    - stun.l.google.com:19302
    - stun1.l.google.com:19302
  enable_loopback_candidate: false
  ips:
    excludes:
      - 10.0.0.0/8
      - 172.16.0.0/12
      - 192.168.0.0/16
      - 172.17.0.0/16
redis:
  sentinel_addresses:
    - "redis-0.redis.livekit:26379"
    - "redis-1.redis.livekit:26379"
  sentinel_master_name: "mymaster"
  dial_timeout: 5000
  read_timeout: 3000
  write_timeout: 3000
  pool_timeout: 4s
  pool_size: 30
keys:
  ***: ***
webhook:
  api_key: '****'
  urls:
    - http://****
turn:
  enabled: true
  relay_range_start: 1024
  relay_range_end: 30000
  udp_port: 3478
  external_tls: true
  domain: ****
logging:
  level: warn
  pion_level: error
  json: false
```


redis config : 
```
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
tcp-keepalive 60
timeout 300
maxclients 10000
```


Livekit console :

Full : https://pastebin.com/Q5xFii9A

```
redis: 2025/03/14 04:53:45 sentinel.go:745: sentinel: discovered new sentinel="10.42.2.194:26379" for master="mymaster"
redis: 2025/03/14 04:53:45 sentinel.go:709: sentinel: new master="mymaster" addr="10.42.1.110:6379"
2025-03-14T04:56:23.306Z	WARN	livekit.transport	rtc/transport.go:830	error reading data channel	{"room": "channel:24273824975425536", "roomID": "RM_9kGK4aGDe6uE", "participant": "97be6dea-84eb-4e35-9282-a57660312651", "pID": "PA_WNS8u5j4Dszm", "remote": false, "transport": "PUBLISHER", "label": "_lossy", "error": "[0xc00181e1e0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
2025-03-14T04:56:23.306Z	WARN	livekit.transport	rtc/transport.go:830	error reading data channel	{"room": "channel:24273824975425536", "roomID": "RM_9kGK4aGDe6uE", "participant": "97be6dea-84eb-4e35-9282-a57660312651", "pID": "PA_WNS8u5j4Dszm", "remote": false, "transport": "PUBLISHER", "label": "_reliable", "error": "[0xc00181e1e0] abort chunk, with following errors: (User Initiated Abort: Close called)"}
2025-03-14T04:56:50.481Z	WARN	livekit.transport	rtc/transport.go:830	error reading data channel	{"room": "channel:24273824975425536", "roomID": "RM_9kGK4aGDe6uE", "participant": "97be6dea-84eb-4e35-9282-a57660312651", "pID": "PA_ybmzWrPTsWgH", "remote": false, "transport": "PUBLISHER", "label": "_lossy", "error": "[0xc0026ec000] abort chunk, with following errors: (User Initiated Abort: Close called)"}
2025-03-14T04:56:50.481Z	WARN	livekit.transport	rtc/transport.go:830	error reading data channel	{"room": "channel:24273824975425536", "roomID": "RM_9kGK4aGDe6uE", "participant": "97be6dea-84eb-4e35-9282-a57660312651", "pID": "PA_ybmzWrPTsWgH", "remote": false, "transport": "PUBLISHER", "label": "_reliable", "error": "[0xc0026ec000] abort chunk, with following errors: (User Initiated Abort: Close called)"}
2025-03-14T07:10:37.164Z	ERROR	livekit	routing/redisrouter.go:221	status update delayed, possible deadlock	{"delay": 3779.150072426, "goroutines": "goroutine 241 [running]:\nruntime/pprof.writeGoroutineStacks({0x1c87400, 0xc0020934a0})\n\t/usr/local/go/src/runtime/pprof/pprof.go:764 +0x6a\nruntime/pprof.writeGoroutine({0x1c87400?, 0xc0020934a0?}, 0x8f1ec6a?)\n....
```

**Comment by biglittlebigben** [comment]
Report is > 6 month old. Please reopen if this still happens in latest versions.
